Simple Yoda gRPC java server and client
PedramPejman/jukebox pull request #147
Opened 2018-01-04 21:27 UTC by PeymanPejman

2018-01-05 09:03 UTC, peddybeats requested changes

2018-01-05 09:03 UTC, peddybeats commented on yoda/Dockerfile
> +RUN apt-get install -yqq maven
2 q flags?

2018-01-05 09:03 UTC, peddybeats commented on yoda/Dockerfile
> +COPY src ./src
I don't understand why this would work.. you're telling docker i have a file (which happens to be of the type "directory") named src in my host FS' root directory; recreate that file (the src directory) at the path /usr/jukebox/yoda/src - which should make the path /usr/jukebox/yoda/src/src.

First make sure this works and then plz lemme know why it does (i.e. which part of the previous analysis was incorrect0

2018-01-05 09:03 UTC, peddybeats commented on yoda/Dockerfile
> +# Make default entrypoint run App's main
s/"run App's main"/"start Yoda's gRPC server"

2018-01-05 09:03 UTC, peddybeats commented on yoda/pom.xml
> +  <modelVersion>4.0.0</modelVersion>
What's the purpose of this?

2018-01-05 09:03 UTC, peddybeats commented on yoda/pom.xml
> +  <version>0.1-SNAPSHOT</version>
Could you please rename this to 0.1

2018-01-05 09:03 UTC, peddybeats commented on yoda/src/main/java/life/jukebox/YodaGrpcClient.java
> + * A simple client that requests a greeting from the YodaGrpcServer.
s/"requests a greeting from"/"sends a greeting request to"

2018-01-05 09:03 UTC, peddybeats commented on yoda/src/main/java/life/jukebox/YodaGrpcClient.java
> +        // Channels are secure by default (via SSL/TLS). For the example we disable TLS to avoid
Please remove this comment

2018-01-05 09:03 UTC, peddybeats commented on yoda/src/main/java/life/jukebox/YodaGrpcClient.java
> +  /** Construct client for accessing RouteGuide server using the existing channel. */
Remove

2018-01-05 09:03 UTC, PedramPejman commented on yoda/src/main/java/life/jukebox/YodaGrpcClient.java
> +    return System.getenv("JB_YODA_SERVICE_PORT") != null ?
Never have literals in your code. If k8s changes their env var scheme, we should have to change it in only 1 place not 1000 places :)

2018-01-05 09:03 UTC, PedramPejman commented on yoda/src/main/java/life/jukebox/YodaGrpcClient.java
> +    YodaGrpcClient client = new YodaGrpcClient(getHost(), getPort());
I like the thinking of encapsulating this two tasks in two methods, but I think they're
1) super light (1 line)
2) only have a single consumer (the YodaGrpcClient constructor)

this is probably the only time I'll say do it in line :) So the beginning of main would look like this:

String host = System.getenv(JB_YODA_SERVICE_HOST) != null ...
int port = ... 

YodaGrpcClient client = new YodaGrpcClient(host, port);

2018-01-05 09:03 UTC, PedramPejman commented on yoda/src/main/java/life/jukebox/YodaGrpcServer.java
> +  private static final int DEFAULT_JB_YODA_SERVICE_PORT = 37000;
Perfect - just for reference this is what every constant should look like

2018-01-05 09:03 UTC, PedramPejman commented on yoda/src/test/java/life/jukebox/AppTest.java
> +package life.jukebox.yoda;
what is this file..?

2018-01-05 19:54 UTC, PeymanPejman commented on yoda/Dockerfile
> +RUN apt-get install -yqq maven
Its q level 2. Show nothing but errors.

2018-01-05 20:12 UTC, PeymanPejman commented on yoda/Dockerfile
> +COPY src ./src
if  <src> is a directory, the entire contents of the directory are copied, including filesystem metadata.

Note: The directory itself is not copied, just its contents.


https://docs.docker.com/engine/reference/builder/#copy

2018-01-05 20:22 UTC, PeymanPejman commented on yoda/pom.xml
> +  <modelVersion>4.0.0</modelVersion>
The minimum requirement for a POM are the following:

project root
modelVersion - should be set to 4.0.0
groupId - the id of the project's group.
artifactId - the id of the artifact (project)
version - the version of the artifact under the specified group

2018-01-06 20:26 UTC, PedramPejman commented on yoda/Dockerfile
> +RUN apt-get install -yqq maven
ack

2018-01-06 20:26 UTC, PedramPejman commented on yoda/Dockerfile
> +COPY src ./src
Got it thanks!

2018-01-06 20:27 UTC, PedramPejman commented on yoda/pom.xml
> +  <modelVersion>4.0.0</modelVersion>
ack

2018-01-06 20:57 UTC, peddybeats approved these changes

2018-01-06 21:01 UTC, merged